# Generated by Django 2.2.24 on 2022-10-31 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='pokemon_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
