# Generated by Django 2.2.24 on 2022-11-10 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0023_auto_20221107_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='previous_evolution',
            new_name='evolution',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='next_evolution',
        ),
    ]
