# Generated by Django 2.2.24 on 2022-11-10 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0031_auto_20221110_2153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='pokemon',
            new_name='pokemons',
        ),
    ]
