# Generated by Django 2.2.24 on 2022-11-17 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0036_auto_20221115_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='pokemon_image',
            new_name='image',
        ),
    ]
